version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: bash -c "cd /app && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - transcriptpro-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    command: npm run dev
    depends_on:
      - backend
    networks:
      - transcriptpro-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=transcriptpro
    networks:
      - transcriptpro-network

volumes:
  postgres_data:

networks:
  transcriptpro-network:
    driver: bridge 